// <auto-generated />
using System;
using GoshenJimenez.Mercadia3.Web.Infrastructure.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoshenJimenez.Mercadia3.Web.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20210413022715_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.Category", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TagLine")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("02b92adc-c0dc-4a87-9aa8-df5d90cf2a00"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(3042),
                            Name = "Category 1",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(3055)
                        },
                        new
                        {
                            Id = new Guid("02b92adc-c0dc-4a87-9aa8-df5d90cf2a01"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(3878),
                            Name = "Category 2",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(3882)
                        },
                        new
                        {
                            Id = new Guid("02b92adc-c0dc-4a87-9aa8-df5d90cf2a02"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(3903),
                            Name = "Category 3",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(3905)
                        });
                });

            modelBuilder.Entity("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.Product", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TagLine")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("254a99bb-bee5-43e0-80dc-e76622110500"),
                            CategoryId = new Guid("02b92adc-c0dc-4a87-9aa8-df5d90cf2a00"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(5682),
                            Description = "Palmolive Naturals White with Milk Whitening Bar Soap 80g 2+1 Value Pack",
                            Name = "Product 1 Soap",
                            Price = 0m,
                            TagLine = "Pag di ka pumuti, iitim ka.",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(5688)
                        },
                        new
                        {
                            Id = new Guid("254a99bb-bee5-43e0-80dc-e76622110501"),
                            CategoryId = new Guid("02b92adc-c0dc-4a87-9aa8-df5d90cf2a00"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(8430),
                            Description = "Global Version Xiaomi Redmi 9A Smartphones 2GB RAM 32GB ROM 6.53″ Intelligent Face Unlock Xiaomi Mall",
                            Name = "Product 2 Cellphone",
                            Price = 0m,
                            TagLine = "Pang ML",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(8434)
                        },
                        new
                        {
                            Id = new Guid("254a99bb-bee5-43e0-80dc-e76622110502"),
                            CategoryId = new Guid("02b92adc-c0dc-4a87-9aa8-df5d90cf2a00"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(8492),
                            Description = "Marby Mini Monay 250g",
                            Name = "Product 3 Bread",
                            Price = 0m,
                            TagLine = "Busog ka agad",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(8493)
                        });
                });

            modelBuilder.Entity("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.ProductTag", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");
                });

            modelBuilder.Entity("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.Tag", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32febb22-f596-4b1e-b0a8-b11ad54be200"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 970, DateTimeKind.Utc).AddTicks(2655),
                            Name = "Tag 1",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 970, DateTimeKind.Utc).AddTicks(3541)
                        },
                        new
                        {
                            Id = new Guid("32febb22-f596-4b1e-b0a8-b11ad54be201"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 970, DateTimeKind.Utc).AddTicks(8157),
                            Name = "Tag 2",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 970, DateTimeKind.Utc).AddTicks(8175)
                        },
                        new
                        {
                            Id = new Guid("32febb22-f596-4b1e-b0a8-b11ad54be203"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 970, DateTimeKind.Utc).AddTicks(8218),
                            Name = "Tag 3",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 970, DateTimeKind.Utc).AddTicks(8219)
                        });
                });

            modelBuilder.Entity("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.User", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa00"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(9780),
                            EmailAddress = "jbeleren@mailinator.com",
                            FirstName = "Jace",
                            LastName = "Beleren",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 973, DateTimeKind.Utc).AddTicks(9784)
                        },
                        new
                        {
                            Id = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa01"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 974, DateTimeKind.Utc).AddTicks(1622),
                            EmailAddress = "lvess@mailinator.com",
                            FirstName = "Liliana",
                            LastName = "Vess",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 974, DateTimeKind.Utc).AddTicks(1626)
                        },
                        new
                        {
                            Id = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa02"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 974, DateTimeKind.Utc).AddTicks(1662),
                            EmailAddress = "cnalaar@mailinator.com",
                            FirstName = "Chandra",
                            LastName = "Nalaar",
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 974, DateTimeKind.Utc).AddTicks(1663)
                        });
                });

            modelBuilder.Entity("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.UserLogin", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d51e388-e135-4c85-b754-e86c2d0500f0"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 987, DateTimeKind.Utc).AddTicks(2987),
                            Key = "Password",
                            Type = 1,
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 13, 987, DateTimeKind.Utc).AddTicks(3009),
                            UserId = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa00"),
                            Value = "$2b$10$PNa3/L3clxgaXkkiNXmmR.Jqnsev7eZ/EBmdASqXpwTD3oxT77SNm"
                        },
                        new
                        {
                            Id = new Guid("0d2698c8-7299-4c2f-8ea0-938c5643f8a9"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 118, DateTimeKind.Utc).AddTicks(8581),
                            Key = "LoginStatus",
                            Type = 0,
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 118, DateTimeKind.Utc).AddTicks(8605),
                            UserId = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa00"),
                            Value = "Active"
                        },
                        new
                        {
                            Id = new Guid("29b4e280-954a-49a4-9de5-3fc2a1fa45d8"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 118, DateTimeKind.Utc).AddTicks(8712),
                            Key = "LoginRetries",
                            Type = 1,
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 118, DateTimeKind.Utc).AddTicks(8713),
                            UserId = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa00"),
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("e8f46698-775f-424c-82ca-ad187f3774c3"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 118, DateTimeKind.Utc).AddTicks(9158),
                            Key = "Password",
                            Type = 1,
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 118, DateTimeKind.Utc).AddTicks(9160),
                            UserId = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa01"),
                            Value = "$2b$10$.5pS8PRo.1LXv2GwJDtIu.UYha5oyIX6O6BCphyCAZaPqEmf/Ax5e"
                        },
                        new
                        {
                            Id = new Guid("49c3dbf5-a719-4f23-9969-8eda6c235b0f"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 237, DateTimeKind.Utc).AddTicks(8616),
                            Key = "LoginStatus",
                            Type = 0,
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 237, DateTimeKind.Utc).AddTicks(8643),
                            UserId = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa01"),
                            Value = "Active"
                        },
                        new
                        {
                            Id = new Guid("6332f116-ad65-4a47-b751-6fbb87588f63"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 237, DateTimeKind.Utc).AddTicks(8710),
                            Key = "LoginRetries",
                            Type = 1,
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 237, DateTimeKind.Utc).AddTicks(8711),
                            UserId = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa01"),
                            Value = "0"
                        },
                        new
                        {
                            Id = new Guid("7f36dcb8-b04f-43fe-b2b0-f280af2a898a"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 237, DateTimeKind.Utc).AddTicks(8765),
                            Key = "Password",
                            Type = 1,
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 237, DateTimeKind.Utc).AddTicks(8766),
                            UserId = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa02"),
                            Value = "$2b$10$bu0MYxYWgclT6GUKOiA1/eO45mO6QXWadAfJ8I6WcebxUeex7hsoC"
                        },
                        new
                        {
                            Id = new Guid("0b307598-d25c-476d-b61d-d2fd8e164d04"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 358, DateTimeKind.Utc).AddTicks(9470),
                            Key = "LoginStatus",
                            Type = 0,
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 358, DateTimeKind.Utc).AddTicks(9544),
                            UserId = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa02"),
                            Value = "Active"
                        },
                        new
                        {
                            Id = new Guid("54545c95-ca91-4323-9122-0f99508ca73f"),
                            CreatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 358, DateTimeKind.Utc).AddTicks(9659),
                            Key = "LoginRetries",
                            Type = 1,
                            UpdatedAt = new DateTime(2021, 4, 13, 2, 27, 14, 358, DateTimeKind.Utc).AddTicks(9690),
                            UserId = new Guid("628019e2-665b-4a4c-ae23-4490ffd4fa02"),
                            Value = "0"
                        });
                });

            modelBuilder.Entity("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.Product", b =>
                {
                    b.HasOne("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.ProductTag", b =>
                {
                    b.HasOne("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.UserLogin", b =>
                {
                    b.HasOne("GoshenJimenez.Mercadia3.Web.Infrastructure.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
